version: "1.0"
name: "oam-uploader"
services:
  public:
    build:
      context: . 
      dockerfile: ./public/Dockerfile.dev
    image: oam-uploader-public:latest
    volumes:
      - ./public:/app
      - ./temporary:/temporary
    ports:
      - "8080:8080"
  private:
    build:
      context: .
      dockerfile: ./private/Dockerfile.dev
    image: oam-uploader-private:latest
    volumes:
      - ./private:/app
      - ./temporary:/temporary
    ports:
      - "7070:7070"

  companion:
      image: transloadit/companion:latest
      env_file: ./companion/.env
      ports:
        - "3020:3020"
      volumes:
        - companion-data:/companion-data
      extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  companion-data: