apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: geotiff-processing-template
spec:
  entrypoint: entry
  onExit: exit-handler
  # Needs changes to be used with an authenticated s3, for now using local stuff
  arguments:
    parameters:
      - name: s3-path
      - name: filename
      - name: bucket
      - name: key
      - name: id
      - name: uuid
      - name: state

  # Volume claim for shared storage for pipeline steps
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi

  templates:
    # DAG for pipeline steps
    - name: entry
      dag:
        tasks:
          - name: download # Download from s3
            template: s3-download
          - name: validate # Validate file
            dependencies: [download]
            template: validate-geotiff
            continueOn:
              failed: true
            hooks:
              running:
                expression: "true"
                template: report-status
                arguments:
                  parameters:
                    - name: step-id
                      value: "validating"
                    - name: message
                      value: "Validating GeoTIFF integrity..."
          - name: convert-to-cog # Convert to cog
            dependencies: [validate]
            template: rio-cogeo-convert
            when: "{{tasks.validate.exitCode}} == 0"
            hooks:
              running:
                expression: "true"
                template: report-status
                arguments:
                  parameters:
                    - name: step-id
                      value: "converting"
                    - name: message
                      value: "Converting file to Cloud Optimized GeoTIFF (COG)..."
          - name: extract-metadata # Extract metadata
            dependencies: [validate]
            template: get-metadata
            when: "{{tasks.validate.exitCode}} == 0"
          - name: upload # Upload cog to s3 
            dependencies: [convert-to-cog]
            template: s3-upload
            when: "{{tasks.validate.exitCode}} == 0 && {{tasks.convert-to-cog.exitCode}} == 0"
            hooks:
              running:
                expression: "true"
                template: report-status
                arguments:
                  parameters:
                    - name: step-id
                      value: "uploading"
                    - name: message
                      value: "Uploading final COG to S3 storage..."
          - name: upload-meta # Upload metadata to aws
            dependencies: [extract-metadata]
            template: meta-upload
            when: "{{tasks.validate.exitCode}} == 0 && {{tasks.extract-metadata.exitCode}} == 0"
          - name: register-stac # Upload metadata to aws
            dependencies: [upload-meta, upload]
            template: register-stac
            when: "{{tasks.validate.exitCode}} == 0 && {{tasks.extract-metadata.exitCode}} == 0"
          - name: cleanup-on-failure # Validation failed
            dependencies: [validate]
            template: cleanup
            when: "{{tasks.validate.exitCode}} == 5 || {{tasks.validate.exitCode}} == 6 || {{tasks.validate.exitCode}} == 7"
    - name: exit-handler
      steps:
        - - name: call-report-api
            template: report-status
            arguments:
              parameters:
                - name: step-id
                  value: "{{workflow.status}}"
                - name: message
                  value: "Processing finished."
            
    - name: s3-download
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args:
          - >
            aws --endpoint-url=http://host.docker.internal:4566 s3 cp {{workflow.parameters.s3-path}}{{workflow.parameters.filename}} /data/input.tif &&
            aws --endpoint-url=http://host.docker.internal:4566 s3api head-object --bucket {{workflow.parameters.bucket}}  --key {{workflow.parameters.key}} --query 'Metadata' > /data/meta.json

        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: validate-geotiff
      container:
        image: validate:dev
        env:
          - name: GDAL_CACHEMAX
            value: "1024"
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "4"
        imagePullPolicy: Never
        command: [python, script.py]
        args: 
          - "/data/input.tif"
        volumeMounts:
          - name: workspace
            mountPath: /data
      # retryStrategy:
      #   limit: "3"
      #   retryPolicy: "OnFailure"
      #   expression: "lastNode.exitCode != 5 && lastNode.exitCode != 6 && lastNode.exitCode != 7"

    - name: rio-cogeo-convert
      container:
        image: convert:dev
        env:
          - name: GDAL_CACHEMAX
            value: "1024"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "4"
        imagePullPolicy: Never
        command: [python, script.py]
        args: 
          - "/data/input.tif"
          - "/data/output.tif"
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: get-metadata
      container:
        image: metadata:dev
        imagePullPolicy: Never
        command: [python, script.py]
        args: 
          - "/data/input.tif"
          - "/data/meta.json"
          - "/data/"
          - "{{workflow.parameters.id}}"
          - "{{workflow.parameters.bucket}}/{{workflow.parameters.key}}"
          - "http://localhost:4566/"
          - "{{workflow.parameters.uuid}}"
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: s3-upload
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args:
          - >
            aws --endpoint-url=http://host.docker.internal:4566 s3 cp /data/output.tif {{workflow.parameters.s3-path}}cog-{{workflow.parameters.filename}}
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: meta-upload
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args:
          - >
            aws --endpoint-url=http://host.docker.internal:4566 s3 cp /data/metadata.json {{workflow.parameters.s3-path}}metadata.json &&
            aws --endpoint-url=http://host.docker.internal:4566 s3 cp /data/thumbnail.png {{workflow.parameters.s3-path}}thumbnail.png
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"
    
    - name: register-stac
      container:
        image: stac:dev
        imagePullPolicy: Never
        env:
          - name: STAC_URL
            value: http://host.docker.internal:7777
        command: [python, script.py]
        args: 
          - "/data/metadata.json"
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"


    - name: cleanup
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args: 
          - >
            aws --endpoint-url=http://host.docker.internal:4566 s3 rm {{workflow.parameters.s3-path}} --recursive;
            curl -X POST http://host.docker.internal:12345/api/v1/workflowstatus \
            -H "Content-Type: application/json" \
            -H "X-Internal-Token: {{workflow.parameters.state}}" \
            -d "{
              \"id\": \"{{workflow.parameters.id}}\",
              \"status\": \"Failed\",
              \"message\": \"Invalid TIF format!\"
            }";
            
            exit 1

    - name: report-status
      inputs:
        parameters:
          - name: step-id
          - name: message
      container:
        image: curlimages/curl:latest
        command: ["sh", "-c"]
        args:
          - |
            curl -X POST http://host.docker.internal:12345/api/v1/workflowstatus \
            -H "Content-Type: application/json" \
            -H "X-Internal-Token: {{workflow.parameters.state}}" \
            -d "{
              \"id\": \"{{workflow.parameters.id}}\",
              \"status\": \"{{inputs.parameters.step-id}}\",
              \"message\": \"{{inputs.parameters.message}}\"
            }"