apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: geotiff-processing-template
spec:
  entrypoint: entry
  # Needs changes to be used with an authenticated s3, for now using local stuff
  arguments:
    parameters:
      - name: s3-path

  # Volume claim for shared storage for pipeline steps
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 25Gi

  templates:
    # DAG for pipeline steps
    - name: entry
      dag:
        tasks:
          - name: download # Download from s3
            template: s3-download
          - name: validate # Validate file
            dependencies: [download]
            template: validate-geotiff
            continueOn:
              failed: true
          - name: convert-to-cog # Convert to cog
            dependencies: [validate]
            template: rio-cogeo-convert
            when: "{{tasks.validate.exitCode}} == 0"
          - name: extract-metadata # Extract metadata
            dependencies: [validate]
            template: get-metadata
            when: "{{tasks.validate.exitCode}} == 0"
          - name: upload # Upload cog to s3 
            dependencies: [convert-to-cog]
            template: s3-upload
            when: "{{tasks.validate.exitCode}} == 0 && {{tasks.convert-to-cog.exitCode}} == 0"
          - name: stac # Upload metadata to pgSTAC
            dependencies: [extract-metadata]
            template: stac-upload
            when: "{{tasks.validate.exitCode}} == 0 && {{tasks.extract-metadata.exitCode}} == 0"
          - name: cleanup-on-failure
            dependencies: [validate]
            template: cleanup
            when: "{{tasks.validate.exitCode}} == 5 || {{tasks.validate.exitCode}} == 6 || {{tasks.validate.exitCode}} == 7"
            
    - name: s3-download
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args: ["aws --endpoint-url=http://host.docker.internal:4566 s3 cp {{workflow.parameters.s3-path}}raw.tif /data/input.tif"]
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: validate-geotiff
      container:
        image: validate:dev
        env:
          - name: GDAL_CACHEMAX
            value: "1024"
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "4"
        imagePullPolicy: Never
        command: [python, script.py]
        args: 
          - "/data/input.tif"
        volumeMounts:
          - name: workspace
            mountPath: /data
      # retryStrategy:
      #   limit: "3"
      #   retryPolicy: "OnFailure"
      #   expression: "lastNode.exitCode != 5 && lastNode.exitCode != 6 && lastNode.exitCode != 7"

    - name: rio-cogeo-convert
      container:
        image: convert:dev
        env:
          - name: GDAL_CACHEMAX
            value: "1024"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "4"
        imagePullPolicy: Never
        command: [python, script.py]
        args: 
          - "/data/input.tif"
          - "/data/output.tif"
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: get-metadata
      container:
        image: metadata:dev
        imagePullPolicy: Never
        command: [python, script.py]
        args: 
          - "/data/input.tif"
          - "/data/"
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: s3-upload
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args:
          - >
            aws --endpoint-url=http://host.docker.internal:4566 s3 cp /data/output.tif {{workflow.parameters.s3-path}}cog.tif
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: stac-upload # Figure this out later...
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args:
          - >
            aws --endpoint-url=http://host.docker.internal:4566 s3 cp /data/metadata.json {{workflow.parameters.s3-path}}metadata.json &&
            aws --endpoint-url=http://host.docker.internal:4566 s3 cp /data/thumbnail.png {{workflow.parameters.s3-path}}thumbnail.png
        volumeMounts:
          - name: workspace
            mountPath: /data
      retryStrategy:
        limit: "3"
        retryPolicy: "OnFailure"

    - name: cleanup
      container:
        image: amazon/aws-cli:latest
        env: # AWS Authentication
          - name: AWS_ACCESS_KEY_ID
            value: test
          - name: AWS_SECRET_ACCESS_KEY
            value: test
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        command: [sh, -c]
        args:
          - >
            aws --endpoint-url=http://host.docker.internal:4566 s3 rm {{workflow.parameters.s3-path}} --recursive &&
            exit 1