apiVersion: batch/v1
kind: Job
metadata:
  name: private-job
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: private-job
    spec:
      restartPolicy: Never
      containers:
        - name: private
          image: oam-uploader-private:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "pipeline/run_pipeline.py"]
          args:
            - "--input"
            - "/mnt/temporary/<file_name>.tif"
          volumeMounts:
            - name: temporary-files
              mountPath: /mnt/temporary
      volumes:
        - name: temporary-files
          persistentVolumeClaim:
            claimName: temp-pvc
