apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public
  template:
    metadata:
      labels:
        app: public
    spec:
      containers:
        - name: public
          image: oam-uploader-public:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: temporary-files
              mountPath: /mnt/temporary
      volumes:
        - name: temporary-files
          persistentVolumeClaim:
            claimName: temp-pvc