apiVersion: apps/v1
kind: Deployment
metadata:
  name: stac-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stac-api
  template:
    metadata:
      labels:
        app: stac-api
    spec:
      hostAliases:
        - ip: "172.26.80.1"
          hostnames:
          - "database"
      containers:
      - name: stac
        image: oam-uploader-stac:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
          - name: POSTGRES_USER
            value: "oam"
          - name: POSTGRES_PASS
            value: "password"
          - name: POSTGRES_DBNAME
            value: "postgis"
          - name: POSTGRES_HOST_READER
            value: "database"
          - name: POSTGRES_HOST_WRITER
            value: "database"
          - name: POSTGRES_PORT
            value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: stac-api # This is what your Python code looks for
spec:
  selector:
    app: stac-api # This tells the service which pods to send traffic to
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082